impulse:
    session:
        # the number of pages that may concurrently exist within the same user session. If a sixth page is requested, the
        # oldest will be deleted. A higher value will result in more allocated memory for the whole user session.
        pages: 5

    # It is recommended to define this length at least with 5. Be aware that a very high
    # id length result in a higher traffic for each request.
    idLength: 5