services:
    # impulse related
    App\UI\Components\:
        resource: '%kernel.project_dir%/src/UI/Components'
        public: true
        # shared:false this is absolutely necessary because WiringAware will retrieve it from the container e.g.
        # 2x times and always receives the same object instead of two
        shared: false
        tags:
            - { name: 'impulse.components', label: 'app', priority: 0 }